# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f98270f928929db05a6173a9e3f310482132bf373f135b8b2580e31a9f8cf772b9f9b95ce88b3f0ef949d951632279597f7b75a423fe049ed7a7e1c0c07e7e33

test:
  secret_key_base: 6a92bf54c6fb52b7f1b3b3e38fdab66c8c43a1ba4e376bff955a2430c85acb0329e7bbfbde89a80fad67661b01b6eff352e8f89eb7bf10eef5f4e7c03bf8407f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
